# Site
title:          rev's homepage
bio:            'Rev A.K.A Aslan</p>23 years old</p>Any pronouns</p>'
description:    "Amateur at everything but passionate nonetheless. Teller of stories such as EniYukie, HYPERFAITH, and most recently, CelShade. Artist of some skill."
picture:        'assets/img/Logo.png'
locale:         en_US
url:            //moonqu4k3.github.io

# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

# Social
# if you don't have any of social below, comment the line.
#email:
twitter: WJIKAQ4KU
#facebook: username
#google:
  #plus: #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#github: username
#stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin: username
#xing: username
instagram: vorepride
#lastfm: username
#tumblr: username
pinterest: moonqu4ke
#foursquare: username
steam: moonqu4ke
#dribbble: username
#youtube: username
#soundcloud: username
#weibo: username
#flickr: username
#codepen: username

# Paginate
# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
